# Project: Calculator
# Makefile created by Dev-C++ 5.10

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Scan.o Print.o
LINKOBJ  = main.o Scan.o Print.o
LIBS     = -L"D:/ProgramS/C/Dev-Cpp/MinGW64/lib" -L"D:/ProgramS/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/ProgramS/C/Dev-Cpp/MinGW64/include" -I"D:/ProgramS/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ProgramS/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/ProgramS/C/Dev-Cpp/MinGW64/include" -I"D:/ProgramS/C/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ProgramS/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/ProgramS/C/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = Calculator.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Scan.o: Scan.cpp
	$(CPP) -c Scan.cpp -o Scan.o $(CXXFLAGS)

Print.o: Print.cpp
	$(CPP) -c Print.cpp -o Print.o $(CXXFLAGS)
